name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Executar testes (pytest)
        run: |
          python -m pytest tests/ -v

      - name: Validar comandos do CLI (help)
        run: |
          python -m src.main --help
          python -m src.main search --help
          python -m src.main figma --help
          python -m src.main repo --help
          python -m src.main status --help
